name: ${NAME_PROJECT:-rabbitmq}

networks:
  rabbitmq:
    driver: bridge

volumes:
  rabbit1:
  rabbit2:
  rabbit3:
  rabbit4:

services:
    loadbalance-nginx:
        image: nginx
        container_name: nginx_loadbalance
        hostname: nginxhost
        restart: always
        ports:
            - '${NGINX_RABBIT_PORT:-5672}:5672'
            - '${NGINX_RABBIT_MANAGER_PORT:-15672}:15672'
        volumes:
          - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
        networks:
          - rabbitmq

    loadbalance-haproxy:
      build:
        context: ./HAProxy/
        dockerfile: Dockerfile
      container_name: haproxy_loadbalance
      hostname: haproxy
      restart: always
      ports:
        - '${HAPROXY_RABBIT_PORT:-5673}:5672'
        - '${HAPROXY_RABBIT_MANAGER_PORT:-15673}:15672'
      volumes:
        - ./HAProxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      networks:
        - rabbitmq

    rabbit1:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: rabbit1
        hostname: rabbit1
        restart: always
        environment:
            - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
            - CLUSTER_MASTER=true
            - HA=true
        volumes:
          - rabbit1:/var/lib/rabbitmq
        networks:
          - rabbitmq
    rabbit2:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: rabbit2
        restart: always
        hostname: rabbit2
        environment:
          - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
          - CLUSTER_WITH=rabbit1
        networks:
          - rabbitmq
        volumes:
          - rabbit2:/var/lib/rabbitmq
    rabbit3:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: rabbit3
        restart: always
        hostname: rabbit3
        environment:
          - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
          - CLUSTER_WITH=rabbit1
        networks:
          - rabbitmq
        volumes:
          - rabbit3:/var/lib/rabbitmq
    rabbit4:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: rabbit4
      restart: always
      hostname: rabbit4
      environment:
        - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
        - CLUSTER_WITH=rabbit1
      networks:
        - rabbitmq
      volumes:
        - rabbit4:/var/lib/rabbitmq

  