version: '3.1'

services:
    
    loadbalance:
        image: nginx
        container_name: nginx_loadbalance
        hostname: nginxhost
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
          - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
        networks:
          - public

    rabbit1:
        image: rabbitmq:management
        container_name: rabbit1
        hostname: rabbit1
        environment:
            - RABBITMQ_ERLANG_COOKIE='mysecret'
        networks:
          - public
    rabbit2:
        image: rabbitmq:management
        container_name: rabbit2
        hostname: rabbit2
        environment:
            - RABBITMQ_ERLANG_COOKIE='mysecret'
        networks:
          - public
    rabbit3:
        image: rabbitmq:management
        container_name: rabbit3
        hostname: rabbit3
        environment:
            - RABBITMQ_ERLANG_COOKIE='mysecret'
        networks:
          - public
          
networks:
  public:
    driver: bridge